version: "1.0"
info:
  model: int-scaffold
packages:
- name: UploadJarsProject
  gitServerName: shshiExternalGitMarch20
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
